### ISSUE TITLE
UEFI Secure Boot: 2 keys unknown to me and not present in the OpenCore Configuration.pdf file

### ISSUE THREAD

**Issue by perez987** [lovegitman/OpenCore-UEFI-Template#1]
Good night, this is an interesting project to be able to build OpenCore from Linux or Windows.
But, in the section about UEFI Secure Boot, I see 2 keys that are unknown to me, `RequireSignature` and `RequireVault`, never seen before.
I can't find them in the OpenCore documentation either. Is there a source to read about them?

It's probably not necessary to add UEFI Secure Boot to your project but, if you prefer to do so, it is a much more complex topic than the short review that you add as you can see, for example, in my repository where you have published recently an issue.

Anyway, congratulations for your work, I'll try it and comment.

**Comment by lovegitman** [comment]
Thanks & will update what to add to config.plist

**Comment by lovegitman** [comment]
It signs bootloaders (.efi) need to update to sign kernel extensions (kexts)

**Comment by lovegitman** [comment]
The RequireSignature key enables the requirement for signed bootloaders and kernel extensions (kexts). Setting it to <true/> ensures that only signed components are loaded.

**Comment by lovegitman** [comment]
The RequireVault key enables the requirement for a vaulted configuration, which provides additional security measures. Setting it to <true/> ensures that the configuration is vaulted.

**Comment by lovegitman** [comment]
The ScanPolicy key sets the policy for scanning unsigned drivers during boot. Setting it to <integer>0</integer> allows all drivers to load regardless of their signatures. You can change this value if you want to enforce stricter policies.

**Comment by perez987** [comment]
Thank you. Learned something new about RequireSignature and RequireVault.

**Comment by lovegitman** [comment]
Updated readme and scripts
